title: Programmer | Code
description: Este é mais um blog dedicado ao desenvolvimento web e ao DevOps
author:
  name: Programmer | Code
  email: "george.salu10@gmail.com"
  url: "https://georgesalu.github.io"

language: "pt-br"

twitter_username: 
github_username:  GeorgeSalu
linkedin_username: george-salu-da-silva-a6b6658a
googleplus_username: 
disqus_username: disqus_RddXqeUbaT

baseurl: /

date_format: "%d/%m/%Y"

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

gems:
  - jekyll-paginate

plugins_dir:
  - jekyll-seo-tag
  - jekyll-paginate

# Custom variables
owner : "SomeHacker"
year : "2020"
