# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: George Salu
email: george.salu10@gmail.com
description: Programmer | Code
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://georgesalu.github.io" # the base hostname & protocol for your site
language: "pt-br"
twitter_username: 
github_username:  GeorgeSalu
linkedin_username: george-salu-da-silva-a6b6658a
paginate: 6
theme-dark: false #Set to true to change to dark website theme

display-author-front-page: false # True if you need show author name and site on home page
display-author-post-page: false # Very usual for guest posts and the infos of author are writen in header of post.md, by default show infos of user settings

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
permalink: /:title/

date_format: "%d/%m/%Y"

authors:
  george:
    name: George Salu
    display_name: george
    gravatar: 
    email: george.salu10@gmail.com
    web: 
    twitter: 
    github: GeorgeSalu